# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24 # or the specific Caddy host IP
  cors_allowed_origins:
    - https://house-of-abbey.github.io

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

sensor:
  - platform: avanza_stock
    stock: 155541
  - platform: avanza_stock
    stock: 19002

prometheus:
  namespace: homeassistant # metrics prefix, e.g. hass_sensor_temperature_c
  filter:
    include_domains:
      - sensor
      - binary_sensor
      - light
      - climate
      - person
      - device_tracker
      - fan
      - switch

person:
  - name: Carl Bäckström
    id: carl_backstrom
    device_trackers:
      - device_tracker.sm_s911b_lan

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
