# This picks a subset of the default_config: preset. More inforation https://www.home-assistant.io/integrations/default_config/
backup: # Backups
# bluetooth: # Bluetooth support
config: # Configuration options
# conversation: # Natural language conversation
dhcp: # DHCP discovery
# energy: # Energy dashboard
file: # File integration
# go2rtc: # Go2RTC media streaming for camera streaming
history: # History and graphs
homeassistant_alerts: # Home Assistant alerts
# cloud: # Home Assistant Cloud
image_upload: # Image uploads
logbook: # Logbook
# media_source: # Media source
mobile_app: # Mobile app support
# my: # My Home Assistant links
ssdp: # SSDP discovery
# stream: # Stream media from cameras and other sources
sun: # Sun tracking
usage_prediction: # Usage prediction of what entities the user is most likely to interact.
usb: # USB support
# webhook: # Webhooks
zeroconf: # Zero-configuration discovery

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

recorder:
  purge_keep_days: 3
  commit_interval: 300
  auto_purge: true

logger:
  default: warning

sensor:
  - platform: avanza_stock
    stock: 155541
  - platform: avanza_stock
    stock: 19002

fan:
  - platform: xiaomi_miio_fan
    name: Xiaomi Fan
    host: 192.168.1.197
    token: !secret xiaomi_fan_token
    model: dmaker.fan.1c

prometheus:
  namespace: homeassistant # metrics prefix, e.g. hass_sensor_temperature_c
  filter:
    include_domains:
      - sensor
      - binary_sensor
      - light
      - climate
      - person
      - device_tracker
      - fan
      - switch

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
